-- BDS OS: Invitations
-- Lets an admin invite team members by email + role.
-- Tokens are generated by the invite-user edge function (service_role) and
-- redeemed by the accept-invitation edge function. PostgREST does not expose
-- INSERT/UPDATE — those must go through edge functions.

ALTER TYPE audit_resource_type ADD VALUE 'invitation';

CREATE TABLE invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email text NOT NULL,
  role user_role NOT NULL,
  token text UNIQUE NOT NULL,
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_invitations_org_pending ON invitations(organization_id) WHERE accepted_at IS NULL;
CREATE INDEX idx_invitations_email_org ON invitations(email, organization_id);

ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;

-- Org members can read their own org's invitations (so admins can show pending invites in UI).
-- INSERT/UPDATE intentionally not exposed to authenticated — must go through edge functions.
CREATE POLICY "invitations_select_own" ON invitations
  FOR SELECT TO authenticated
  USING (organization_id = get_user_organization_id());
