-- Email-based invitations with tokens. Tokens generated by invite-user
-- (service role) and redeemed by accept-invitation. PostgREST INSERT/UPDATE
-- not exposed. Coexists with Lovable's existing company_members.invited_by
-- simple flow.

CREATE TABLE public.invitations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL REFERENCES public.companies(id) ON DELETE CASCADE,
  email text NOT NULL,
  role public.company_role NOT NULL,
  token text UNIQUE NOT NULL,
  invited_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  expires_at timestamptz NOT NULL,
  accepted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_invitations_company_pending ON public.invitations(company_id) WHERE accepted_at IS NULL;
CREATE INDEX idx_invitations_email_company ON public.invitations(email, company_id);

ALTER TABLE public.invitations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "invitations_select_admin"
ON public.invitations FOR SELECT TO authenticated
USING (public.has_company_role(auth.uid(), company_id, ARRAY['owner','admin']::public.company_role[]));
-- INSERT/UPDATE intentionally not exposed to authenticated; use edge functions.
